name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Version
      run: echo "VERSION=$(cat ./castleblock-service/package.json | grep '"version"' | head -n 1 | awk '{print $2}' | sed 's/"//g; s/,//g')" >> $GITHUB_ENV
    - name: Print Version
      run: echo $VERSION
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  
    - name: Build Docker image
      run: docker build ./castleblock-service -t "castleblock:${VERSION}"
    - name: Push to Dockerhub
      run: docker push "castleblock:${VERSION}"
