name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      run: sudo apt update; sudo apt install nodejs;
    - name: Get version number
      run: VERSION=$(node -p "require('./castleblock-service/package.json').version")
    - name: Build Docker image
      run: docker build ./castleblock-service -t "castleblock:${VERSION}"
